version: '3'

services:
  django:
    labels:
      shipyard.route: '/'
    build: .
    ports:
      - '8000:8000'
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_CALLBACK=${GOOGLE_CLIENT_CALLBACK}
